// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfveIn4PcqoN4CU7e0TKd1qoa4f9NzHvA',
    appId: '1:922688829251:web:846921ba50c77f8cd7e1f6',
    messagingSenderId: '922688829251',
    projectId: 'spires-2bdda',
    authDomain: 'spires-2bdda.firebaseapp.com',
    storageBucket: 'spires-2bdda.appspot.com',
    measurementId: 'G-33T8NTELJE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOjg3aE5OSlV6oAhfYsWJ8aYSLfjfysrw',
    appId: '1:922688829251:android:7e1990fe95621ce0d7e1f6',
    messagingSenderId: '922688829251',
    projectId: 'spires-2bdda',
    storageBucket: 'spires-2bdda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXAeCtSS9MaJe0BESXHa7deCrdLejd33E',
    appId: '1:922688829251:ios:5105a4c255c889a2d7e1f6',
    messagingSenderId: '922688829251',
    projectId: 'spires-2bdda',
    storageBucket: 'spires-2bdda.appspot.com',
    iosBundleId: 'com.example.spiresApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXAeCtSS9MaJe0BESXHa7deCrdLejd33E',
    appId: '1:922688829251:ios:5105a4c255c889a2d7e1f6',
    messagingSenderId: '922688829251',
    projectId: 'spires-2bdda',
    storageBucket: 'spires-2bdda.appspot.com',
    iosBundleId: 'com.example.spiresApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfveIn4PcqoN4CU7e0TKd1qoa4f9NzHvA',
    appId: '1:922688829251:web:0e21ad4a6bab67b2d7e1f6',
    messagingSenderId: '922688829251',
    projectId: 'spires-2bdda',
    authDomain: 'spires-2bdda.firebaseapp.com',
    storageBucket: 'spires-2bdda.appspot.com',
    measurementId: 'G-XK7K65Q0R9',
  );
}
