// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCl78JfhiKi3jBROr0z2ZZrKMVgRBe90U',
    appId: '1:140810524533:web:1efa34cc7df0cc0671253c',
    messagingSenderId: '140810524533',
    projectId: 'spires-recruit',
    authDomain: 'spires-recruit.firebaseapp.com',
    storageBucket: 'spires-recruit.firebasestorage.app',
    measurementId: 'G-GGD2KETD3L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwnSyBy-8MATRosfViST-zq6jSJbrlQo0',
    appId: '1:140810524533:android:c4c037ceace83ca371253c',
    messagingSenderId: '140810524533',
    projectId: 'spires-recruit',
    storageBucket: 'spires-recruit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpFk5jB_1i_EZCc4vrUcRd8ryCg0mgXd8',
    appId: '1:140810524533:ios:f01f76cb307719ef71253c',
    messagingSenderId: '140810524533',
    projectId: 'spires-recruit',
    storageBucket: 'spires-recruit.firebasestorage.app',
    iosBundleId: 'com.atc.spiresApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpFk5jB_1i_EZCc4vrUcRd8ryCg0mgXd8',
    appId: '1:140810524533:ios:61d35de325f5603e71253c',
    messagingSenderId: '140810524533',
    projectId: 'spires-recruit',
    storageBucket: 'spires-recruit.firebasestorage.app',
    iosBundleId: 'com.example.spiresApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCl78JfhiKi3jBROr0z2ZZrKMVgRBe90U',
    appId: '1:140810524533:web:ce4b54d015f3fc6271253c',
    messagingSenderId: '140810524533',
    projectId: 'spires-recruit',
    authDomain: 'spires-recruit.firebaseapp.com',
    storageBucket: 'spires-recruit.firebasestorage.app',
    measurementId: 'G-ZC9WHT0XHR',
  );

}